# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_ut_init <- function(path) {
    .Call('_units_R_ut_init', PACKAGE = 'units', path)
}

R_ut_set_encoding <- function(sys_, enc_str) {
    invisible(.Call('_units_R_ut_set_encoding', PACKAGE = 'units', sys_, enc_str))
}

R_ut_is_parseable <- function(sys_, str) {
    .Call('_units_R_ut_is_parseable', PACKAGE = 'units', sys_, str)
}

R_ut_are_convertible <- function(sys_, a, b) {
    .Call('_units_R_ut_are_convertible', PACKAGE = 'units', sys_, a, b)
}

R_ut_convert_doubles <- function(sys_, from, to, val) {
    .Call('_units_R_ut_convert_doubles', PACKAGE = 'units', sys_, from, to, val)
}

R_ut_new_dimensionless_unit <- function(sys_, name) {
    invisible(.Call('_units_R_ut_new_dimensionless_unit', PACKAGE = 'units', sys_, name))
}

R_ut_scale <- function(sys_, from, to, factor) {
    invisible(.Call('_units_R_ut_scale', PACKAGE = 'units', sys_, from, to, factor))
}

R_ut_offset <- function(sys_, from, to, factor) {
    invisible(.Call('_units_R_ut_offset', PACKAGE = 'units', sys_, from, to, factor))
}

R_ut_get_symbol <- function(sys_, str) {
    .Call('_units_R_ut_get_symbol', PACKAGE = 'units', sys_, str)
}

R_ut_get_name <- function(sys_, str) {
    .Call('_units_R_ut_get_name', PACKAGE = 'units', sys_, str)
}

